ARG ELK_VERSION

ARG TEST_KAFKA_TOPIC_NAME
ARG TEST_KAFKA_ADDRESS
ARG TEST_ELK_INDEX_PATTERN

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
